---
title: "'Exit Try'는 'Try' 문 내부에만 사용할 수 있습니다."
ms.date: 07/20/2015
f1_keywords:
- vbc30393
- bc30393
helpviewer_keywords:
- BC30393
ms.assetid: b8651df3-a32f-478c-a6d8-aa0ef584155f
ms.openlocfilehash: 56bc58a74d0ed53e10349636a703b98aae26af9d
ms.sourcegitcommit: 6b308cf6d627d78ee36dbbae8972a310ac7fd6c8
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 01/23/2019
ms.locfileid: "54720667"
---
# <a name="exit-try-can-only-appear-inside-a-try-statement"></a>'Exit Try'는 'Try' 문 내부에만 사용할 수 있습니다.
`Exit Try` 는 `Try` 블록 문에서만 나올 수 있습니다. 중복 `Exit Try` 문이 있거나 또는 `Exit Try` 문이 해당 `Try` 블록의 경계를 벗어난 곳에 나타납니다.  
  
 **오류 ID:** BC30393  
  
## <a name="to-correct-this-error"></a>이 오류를 해결하려면  
  
1.  불필요한 `Exit Try` 문을 찾아서 제거합니다.  
  
2.  이동 된 `Exit Try` 코드 내에서 적절 한 위치로 문입니다.  
  
## <a name="see-also"></a>참고자료
- [Try...Catch...Finally 문](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)

