---
title: "&#39; Throw&#39; 문 외부에서 피연산자를 생략할 수 없습니다는 &#39; Catch &#39; 문 또는 내부는 &#39; 마지막으로 &#39; 문"
ms.date: 07/20/2015
ms.prod: .net
ms.technology:
- devlang-visual-basic
ms.topic: article
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
caps.latest.revision: 
author: dotnet-bot
ms.author: dotnetcontent
ms.openlocfilehash: 5fa3be0ca47a4158b3abeef9801148e3f19d3b36
ms.sourcegitcommit: c0dd436f6f8f44dc80dc43b07f6841a00b74b23f
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 01/19/2018
---
# <a name="39throw39-statement-cannot-omit-operand-outside-a-39catch39-statement-or-inside-a-39finally39-statement"></a>&#39; Throw&#39; 문 외부에서 피연산자를 생략할 수 없습니다는 &#39; Catch &#39; 문 또는 내부는 &#39; 마지막으로 &#39; 문
`Throw` 문 외부의 `Catch` 문에서 예외 개체의 이름을 제공해야 합니다.  
  
 **오류 ID:** BC30666  
  
## <a name="to-correct-this-error"></a>이 오류를 해결하려면  
  
1.  `System.Exception`에서 파생된 예외 개체의 이름을 지정합니다.  
  
2.  `Throw` 문이 `Catch` 블록 내부에 있도록 코드를 재구성합니다.  
  
## <a name="see-also"></a>참고 항목  
 [Throw 문](../../visual-basic/language-reference/statements/throw-statement.md)  
 [Try...Catch...Finally 문](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 [Visual Basic의 예외 클래스](http://msdn.microsoft.com/library/9aac396f-34ca-4afb-8e6c-e523cb690ba9)  
 [예외 및 Visual Basic에서의 오류 처리](http://msdn.microsoft.com/library/3e351e73-cf23-40ab-8b60-05794160529e)
