---
title: "&#39; Catch &#39; 뒤에 나타날 수 없습니다 &#39; 마지막으로 &#39; 내에서 한 &#39; Try &#39; 문"
ms.date: 07/20/2015
ms.prod: .net
ms.technology: devlang-visual-basic
ms.topic: article
f1_keywords:
- vbc30379
- bc30379
helpviewer_keywords: BC30379
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
caps.latest.revision: "8"
author: dotnet-bot
ms.author: dotnetcontent
ms.openlocfilehash: 9f0bd039857b375808da19817ea70d24e6208417
ms.sourcegitcommit: 34ec7753acf76f90a0fa845235ef06663dc9e36e
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 12/21/2017
---
# <a name="39catch39-cannot-appear-after-39finally39-within-a-39try39-statement"></a>&#39; Catch &#39; 뒤에 나타날 수 없습니다 &#39; 마지막으로 &#39; 내에서 한 &#39; Try &#39; 문
`Catch` 문이 코드에서 `Finally` 문 블록을 끝내는 `Try` 뒤에 나타납니다. `Catch` 는 `Try...Catch...Finally` 문 블록 내에서 사용해야 합니다.  
  
 **오류 ID:** BC30379  
  
## <a name="to-correct-this-error"></a>이 오류를 해결하려면  
  
1.  `Catch` 문을 코드의 더 적절한 위치로 이동합니다.  
  
## <a name="see-also"></a>참고 항목  
 [Try...Catch...Finally 문](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 
