---
title: '&#39;Catch&#39; 후 나타날 수 없습니다 &#39;마지막&#39; 내에서 한 &#39;시도&#39; 문'
ms.date: 07/20/2015
f1_keywords:
- vbc30379
- bc30379
helpviewer_keywords:
- BC30379
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
ms.openlocfilehash: f0eec8db52d71fb61a85a2811f4904c4ad745b67
ms.sourcegitcommit: 3d5d33f384eeba41b2dff79d096f47ccc8d8f03d
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 05/04/2018
ms.locfileid: "33611452"
---
# <a name="39catch39-cannot-appear-after-39finally39-within-a-39try39-statement"></a>&#39;Catch&#39; 후 나타날 수 없습니다 &#39;마지막&#39; 내에서 한 &#39;시도&#39; 문
`Catch` 문이 코드에서 `Finally` 문 블록을 끝내는 `Try` 뒤에 나타납니다. `Catch` 는 `Try...Catch...Finally` 문 블록 내에서 사용해야 합니다.  
  
 **오류 ID:** BC30379  
  
## <a name="to-correct-this-error"></a>이 오류를 해결하려면  
  
1.  `Catch` 문을 코드의 더 적절한 위치로 이동합니다.  
  
## <a name="see-also"></a>참고 항목  
 [Try...Catch...Finally 문](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 
